#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2	-d	1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-2 -d	1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-1 -d  1 2 3 4 5 6 7 8 9 0

bspc config border_width     2
bspc config window_gap		 8
bspc config bottom_padding	-5
bspc config top_padding		-5
bspc config left_padding	-5
bspc config right_padding	-5
bspc config -m HDMI-2 top_padding 25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color	"#ff0000"
bspc config active_border_color		"#00aaaa"
bspc config normal_border_color		"#00aaaa"

exec discord &
exec telegram-desktop &
exec thunderbird &
exec picom --config=$HOME/.config/picom/picom.conf --experimental-backend &
exec dunst &
exec ~/.config/polybar/launch.sh &
